void main(
  float4 aPosition : POSITION
, float2 aTexCoord : TEXCOORD
, float3 aInput1 : COLOR0
, float3 aInput2 : COLOR1
, out float4 vPosition : POSITION
, out float2 vTexCoord : TEXCOORD0
, out float3 vInput1 : COLOR0
, out float3 vInput2 : COLOR1
, uniform float4x4 uViewport
) {
vTexCoord = aTexCoord;
vInput1 = aInput1;
vInput2 = aInput2;
float4 pos = mul(aPosition, uViewport);
pos.xyz /= pos.w;
vPosition = float4(pos.xyz, aPosition.w);
}

