void main(
  float4 aPosition : POSITION
, float2 aTexCoord : TEXCOORD
, float4 aInput1 : COLOR0
, out float4 vPosition : POSITION
, out float2 vTexCoord0 : TEXCOORD0
, out float2 vTexCoord1 : TEXCOORD1
, out float4 vInput1 : COLOR0
, uniform float4 uViewScale
, uniform float4 uViewOfs
) {
vTexCoord0 = aTexCoord;
vTexCoord1 = aTexCoord;
vInput1 = aInput1;
float4 pos = aPosition * uViewScale;
pos.xyz = pos.xyz / pos.w + uViewOfs.xyz;
vPosition = pos;
}

