void main(
  float4 aPosition : POSITION
, float2 aTexCoord : TEXCOORD
, float4 aInput1 : COLOR0
, out float4 vPosition : POSITION
, out float2 vTexCoord0 : TEXCOORD0
, out float2 vTexCoord1 : TEXCOORD1
, out float4 vInput1 : COLOR0
, uniform float4x4 uViewport
) {
vTexCoord0 = aTexCoord;
vTexCoord1 = aTexCoord;
vInput1 = aInput1;
float4 pos = mul(aPosition, uViewport);
pos.xyz /= pos.w;
vPosition = float4(pos.xyz, aPosition.w);
}

