#!/usr/bin/env python3

import os
import sys

print('/* this file was generated by gen_shaderdb.py, do not edit manually */\n')

for arg in sys.argv[1:]:
    print('extern const XguTransformProgramInstruction _' + arg + '_vs_inst[];')
    print('extern const uint32_t _' + arg + '_vs_size;')
    print('extern uint32_t *_' + arg + '_ps_combiner(uint32_t *);')

print('static const struct CompiledShader shader_objs[] = {')

for arg in sys.argv[1:]:
    print('    {{ 0x{0}, _{0}_vs_inst, &_{0}_vs_size, _{0}_ps_combiner }},'.format(arg))

print('};\n')

print('static const u32 num_shader_objs = sizeof(shader_objs) / sizeof(shader_objs[0]);\n')

