#!/usr/bin/env python3

import os
import sys

print('/* this file was generated by gen_shaderdb.py, do not edit manually */\n')

for arg in sys.argv[1:]:
    print('extern const u8 _' + arg + '_vpo[];')
    print('extern const u32 _' + arg + '_vpo_size;')
    print('extern const u8 _' + arg + '_fpo[];')
    print('extern const u32 _' + arg + '_fpo_size;\n')

print('static const struct ShaderData {')
print('    u32 shader_id;')
print('    const u8 *vpo_data;')
print('    const u8 *fpo_data;')
print('    const u32 *vpo_size;')
print('    const u32 *fpo_size;')
print('} shader_objs[] = {')

for arg in sys.argv[1:]:
    print('    {{ 0x{0}, _{0}_vpo, _{0}_fpo, &_{0}_vpo_size, &_{0}_fpo_size }},'.format(arg))

print('};\n')

print('static const u32 num_shader_objs = sizeof(shader_objs) / sizeof(shader_objs[0]);\n')

